services:
  backend:
    build: ./B
    ports:
      - "8000:8000"
    volumes:
      - ./B:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./F
    ports:
      - "5173:5173"
    volumes:
      - ./F:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mysql_data: